### ISSUE TITLE
Fan control support for new models

### ISSUE THREAD

**Issue by ohlawdie** [determ1ne/OmenHubLight#1]
Hi @determ1ne great idea and thanks for publicizing your tooling! I've been looking for an alternative to Omen Gaming Hub or at least a Powershell script to run over some cli for my fans...tired of pressing windows key - typing omen - and then navigating to the fan slider. Unfortunately, this doesn't appear to be working on my HP Omen 15-ek0xxx. I did just get a set of replacement fans as well but I'm assuming it's the exact same type as the stock set of fans and I'm on Windows 10.0.19043 Build 19043 (if that matters whatsoever) lol - would really like to help troubleshoot if possible, thanks!

**Comment by determ1ne** [comment]
If you got a slider in the fan control, it means that your omen computer is using the newer fan control protocol, which internally represents eight options.
My computer is older so I can't test it, but I'll try to support it soon.

**Comment by determ1ne** [comment]
The new fan control policy is much more complex, and I can't ensure if it works or breaks anything without test. I made an experimental script for programmatically controlling your fan, and you can test it out at your own risk.

1. Set fan control to manual in OMEN Gaming Hub
2. Download and install PowerShell 7
3. Download and extract the project binaries
4. Get the min and max rpm of your fan
```powershell
Add-Type -Path .\HpShimLibrary.dll
$hsaClient = New-Object HP.Omen.OmenCommonLib.OMENHsaClient
$dataArr = New-Object byte[] 4
$fanTable = $hsaClient.BiosWmiCmd_Get(131080, 47, $dataArr, 128)
``` 
The format of $fanTable is `[NumofFanModes, ModeDb1, ModeRpm1, ModeDb2, ModeRpm2...]`. Then you can get a range of rpm for tuning your fan,
5. Run the following PowerShell script, set $cpuFanRpm to whatever you want
```powershell
$cpuFanRpm = [byte] 100
$arg2 = [byte]($cpuFanRpm - 2)
Add-Type -Path .\HpShimLibrary.dll
$hsaClient = New-Object HP.Omen.OmenCommonLib.OMENHsaClient
$dataArr = [byte[]] @($cpuFanRpm, $arg2)
$hsaClient.BiosWmiCmd_Set(131080, 46, $dataArr)
```

**Comment by ohlawdie** [comment]
Thanks @determ1ne sorry for the late reply back to your comments thank you for the PS! I'm actually in the process of reinstating windows on my machine so I'll let you know if I blow up the fans :D but the above looks 'easy' to tweak in your project and should be a-ok! Thank you again!

**Comment by prajaybasu** [comment]
I stumbled across this trying to find a solution to keep my HP Envy 14 (8815/ "StarcraftDiscrete") in performance mode without HP Command Center. Windows Update auto installs HP spyware and HP CC just crashes for me in Windows 11. 


My question is, is any external dependency from HP really needed if the new models use WMI? [System.Management](https://docs.microsoft.com/en-us/dotnet/api/system.management?view=dotnet-plat-ext-3.1) or [Microsoft.Management.Infrastructure](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/mi-managed-api/hh832958(v=vs.85)) should work right?


  Edit: Seems like [this](https://github.com/determ1ne/OmenHubLight/blob/master/HPShimLibrary/Hp.Ohl.WmiService/HpBiosIntHelper.cs) was what I was exactly looking for. Couldn't find this in the managed code after decompiling and I wasn't ready to spend the effort for the native code

**Comment by determ1ne** [comment]
> I stumbled across this trying to find a solution to keep my HP Envy 14 (8815/ "StarcraftDiscrete") in performance mode without HP Command Center. Windows Update auto installs HP spyware and HP CC just crashes for me in Windows 11.
> 
> My question is, is any external dependency from HP really needed if the new models use WMI? [System.Management](https://docs.microsoft.com/en-us/dotnet/api/system.management?view=dotnet-plat-ext-3.1) or [Microsoft.Management.Infrastructure](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/mi-managed-api/hh832958(v=vs.85)) should work right?
> 
> Edit: Seems like [this](https://github.com/determ1ne/OmenHubLight/blob/master/HPShimLibrary/Hp.Ohl.WmiService/HpBiosIntHelper.cs) was what I was exactly looking for. Couldn't find this in the managed code after decompiling and I wasn't ready to spend the effort for the native code

@prajaybasu No, you're going the wrong way, just hack into the HP App from Microsoft Store. To call WMI-ACPI Method, the program needs admin privilege. The HP software driver installed by Windows Update is just the backend for this. The Store App uses RPC to pass arguments, and the security verification can be patched by OmenDriverPatcher.

**Comment by prajaybasu** [comment]
> @prajaybasu No, you're going the wrong way, just hack into the HP App from Microsoft Store. To call WMI-ACPI Method, the program needs admin privilege. The HP software driver installed by Win

I just created a lightweight app to force full performance for my Envy instead of all that. Worked fine for me, don't need to deal with RPC or any drivers for XTU/LPC (since my model only uses WMI).  I'm gonna update it to suit my needs.

https://github.com/prajaybasu/ThermalControl

**Comment by determ1ne** [comment]
> > @prajaybasu No, you're going the wrong way, just hack into the HP App from Microsoft Store. To call WMI-ACPI Method, the program needs admin privilege. The HP software driver installed by Win
> 
> I just created a lightweight app to force full performance for my Envy instead of all that. Worked fine for me, don't need to deal with RPC or any drivers for XTU/LPC (since my model only uses WMI). I'm gonna update it to suit my needs.
> 
> https://github.com/prajaybasu/ThermalControl

RPC is for GUI without admin privilege, XTU is for overclocking. OmenHubLight uses only WMI, as you can see in the code.

**Comment by ohlawdie** [comment]
evening again @determ1ne, I may start to get back to 'professionally' being on/at my PC & I was wondering if you could possibly continue to help me troubleshoot as to why your lovely program doesn't work with my (Windows 11) laptop. For the sake of covalence, I'm using the maximum setting and on the right-hand side of the picture below -> I must have the eight-option rpm slider from low<->high ?
![image](https://user-images.githubusercontent.com/30779615/174502234-f34ad8a2-1683-4895-bb38-f5a63e78eb02.png)

if nothing more can be done I understand -- thank you

**Comment by RotateMe** [comment]
There seem to be a lot of different versions, in my case I have only "MAX" and "AUTO", but not manual. Since this was also not supported by this (very nice) tool, I dug my teeth into adding the MAX/AUTO option to OmenHubLight.

By decompiling the DLLs in the OmenGamingHub folder I was able to find the BIOS call to change that setting, in terms of OmenHubLight code this would be:

```
        public enum MaxFanMode
        {
            Off,
            On,
        }

        private void SetMaxFanMode(MaxFanMode maxFanMode)
        {
            byte[] inputData = new byte[1];
            inputData[0] = (byte)maxFanMode;
            var res = hsaClient.BiosWmiCmd_Set(131080, 39, inputData);
        }
```

You can try if that also works in your case. Simply bind it to a CheckBox or a Button or so.

I went even further and added something very helpful (for me at least), which is that I automatically set it to MAX, when my temperatures go above 92 Degrees (the value can be changed) and automatically returns to AUTO, when my temperatures are below 80 Degrees again.

If people are interested I'll try to create a Fork and a Pull Request.

**Comment by determ1ne** [comment]
> evening again @determ1ne, I may start to get back to 'professionally' being on/at my PC & I was wondering if you could possibly continue to help me troubleshoot as to why your lovely program doesn't work with my (Windows 11) laptop. For the sake of covalence, I'm using the maximum setting and on the right-hand side of the picture below -> I must have the eight-option rpm slider from low<->high ? ![image](https://user-images.githubusercontent.com/30779615/174502234-f34ad8a2-1683-4895-bb38-f5a63e78eb02.png)
> 
> if nothing more can be done I understand -- thank you

Technically, HP uses BIOS WMI to notice the hardware, and the tool, built on top of decompiling OMEN Gaming Hub, directly calls Windows WMI API without any HP software component.
As @RotateMe pointed out, thermal control methods may be different among laptop models. The buttons and sliders seem alike, but the code behind them(specifically, parameters used in the bios command) does not. It's really hard to cover every situation, so I recommend you to decompile and do the port yourself.
